name: Test actions
run-name: Testing

on:
  repository_dispatch:
    types: testing

jobs:
  dbm-offline-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Run DBM-Offline
        uses: DeadlyBossMods/DBM-Offline@main
        with:
          dbm-mod-repo: DeadlyBossMods/DBM-Vanilla
          dbm-mod-ref: cf5701677b430ece1af38b3ed8dcc3a2047126e0
          dbm-mod-base-ref: d3dfc8ee7ba5f43c993cfdfe484da4af2fedf718
          upload-repo: emmericp/test-github-actions
          upload-token: ${{ secrets.GH_TOKEN }}
